apiVersion: v1
kind: Namespace
metadata:
  labels:
    api: tor
    control-plane: controller-manager
  name: tor-system
---
apiVersion: v1
kind: Service
metadata:
  name: tor-controller-manager
  namespace: tor-system
  labels:
    api: tor
    control-plane: controller-manager
spec:
  clusterIP: None
  selector:
    api: tor
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tor-controller-manager
  namespace: tor-system
  labels:
    control-plane: controller-manager
    kubebuilder.k8s.io: master
spec:
  selector:
    matchLabels:
      api: tor
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        api: tor
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /root/controller-manager
        args:
        - --enable-leader-election
        image: controller:latest
        name: controller-manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
