apiVersion: v1
kind: Namespace
metadata:
  name: tor-system
  labels:
    api: tor
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  name: tor-controller-manager
  namespace: tor-system
  labels:
    api: tor
    control-plane: controller-manager
spec:
  clusterIP: None
  selector:
    api: tor
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tor-controller-manager
  namespace: tor-system
  labels:
    control-plane: controller-manager
    kubebuilder.k8s.io: master
spec:
  selector:
    matchLabels:
      api: tor
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        api: tor
        control-plane: controller-manager
    spec:
      containers:
      - name: controller-manager
        image: quay.io/tor-operator/controller-manager:latest
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRole
#metadata:
#  name: tor
#  labels:
#    api: tor
#    control-plane: controller-manager
#rules:
#  - apiGroups:
#      - ""
#    resources:
#      - pods
#    verbs:
#      - get
#      - list
#      - watch
#      - create
#      - update
#      - patch
#      - delete
#  - apiGroups:
#      - apps
#    resources:
#      - deployments
#    verbs:
#      - get
#      - list
#      - watch
#      - create
#      - update
#      - patch
#      - delete
#  - apiGroups:
#      - ""
#    resources:
#      - services
#    verbs:
#      - get
#      - list
#      - watch
#      - create
#      - update
#      - patch
#      - delete
#  - apiGroups:
#      - ""
#    resources:
#      - secrets
#    verbs:
#      - get
#      - list
#      - watch
#      - create
#      - update
#      - patch
#      - delete
#  - apiGroups:
#      - ""
#    resources:
#      - serviceaccounts
#    verbs:
#      - get
#      - list
#      - watch
#      - create
#      - update
#      - patch
#      - delete
#  - apiGroups:
#      - rbac.authorization.k8s.io
#    resources:
#      - roles
#    verbs:
#      - get
#      - list
#      - watch
#      - create
#      - update
#      - patch
#      - delete
#  - apiGroups:
#      - rbac.authorization.k8s.io
#    resources:
#      - rolebindings
#    verbs:
#      - get
#      - list
#      - watch
#      - create
#      - update
#      - patch
#      - delete
#  - apiGroups:
#      - ""
#    resources:
#      - events
#    verbs:
#      - get
#      - list
#      - watch
#      - create
#      - update
#      - patch
#      - delete
#  - apiGroups:
#      - tor.k8s.io
#    resources:
#      - '*'
#    verbs:
#      - '*'
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: tor
#  labels:
#    api: tor
#    control-plane: controller-manager
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: tor
#subjects:
#  - kind: ServiceAccount
#    name: default
#    namespace: tor-system
#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: tor
#  labels:
#    api: tor
#    control-plane: controller-manager
#---