# permissions for end users to edit onionservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: onionservice-editor-role
rules:
- apiGroups:
  - tor.k8s.io
  resources:
  - onionservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tor.k8s.io
  resources:
  - onionservices/status
  verbs:
  - get
